# Generated by Django 3.2.7 on 2021-10-21 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название промышленного здания')),
                ('index', models.CharField(blank=True, max_length=10, null=True, verbose_name='Индекс')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Промышленное здание',
                'verbose_name_plural': 'Промышленные здания',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название станции')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Street',
                'verbose_name_plural': 'Streets',
                'db_table': 'street',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NO', models.FloatField(blank=True, null=True, verbose_name='NO')),
                ('NO2', models.FloatField(blank=True, null=True, verbose_name='NO2')),
                ('CO', models.FloatField(blank=True, null=True, verbose_name='CO')),
                ('MP10', models.FloatField(blank=True, null=True, verbose_name='MP10')),
                ('MP25', models.FloatField(blank=True, null=True, verbose_name='MP2.5')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='Скорость ветра')),
                ('direction', models.FloatField(blank=True, null=True, verbose_name='Направление ветра')),
                ('temp', models.FloatField(blank=True, null=True, verbose_name='Температура')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Давление')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Влажность')),
                ('precipitation', models.FloatField(blank=True, null=True, verbose_name='Осадки')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата и время')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesscard.station')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные',
            },
        ),
        migrations.CreateModel(
            name='AddPollution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('character', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('house_number', models.CharField(blank=True, max_length=8, null=True)),
                ('comment', models.CharField(blank=True, max_length=120, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('name_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesscard.industry')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesscard.street')),
            ],
            options={
                'verbose_name': 'AddPollution',
                'verbose_name_plural': 'AddPollutions',
                'db_table': 'add_pollution',
            },
        ),
    ]
