# Generated by Django 3.2.7 on 2021-10-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesscard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_build', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ид работ')),
                ('status', models.CharField(blank=True, max_length=300, null=True, verbose_name='Статус')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название')),
                ('func', models.CharField(blank=True, max_length=300, null=True, verbose_name='Функция')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('dev', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подрядчик')),
                ('end_year', models.CharField(blank=True, max_length=300, null=True, verbose_name='Год окончания работ')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Стройка',
                'verbose_name_plural': 'Стройки',
            },
        ),
        migrations.AlterModelOptions(
            name='addpollution',
            options={'verbose_name': 'Заявления о загрязнениях', 'verbose_name_plural': 'Заявление о загрязнении'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'Улица', 'verbose_name_plural': 'Улицы'},
        ),
        migrations.AlterField(
            model_name='addpollution',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Подтверждение жалобы'),
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Время')),
                ('NO', models.FloatField(blank=True, null=True, verbose_name='NO')),
                ('NO2', models.FloatField(blank=True, null=True, verbose_name='NO2')),
                ('CO', models.FloatField(blank=True, null=True, verbose_name='CO')),
                ('MP10', models.FloatField(blank=True, null=True, verbose_name='MP10')),
                ('MP25', models.FloatField(blank=True, null=True, verbose_name='MP2.5')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesscard.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Предсказание',
                'verbose_name_plural': 'Предсказания',
            },
        ),
    ]
